version: "3.9"
services:
  
  cte:
    container_name: cte_backend
    build:
      context: .
      dockerfile: dockerfile
      args:
        PHP_VERSION: '7.4.33-fpm'
        user: Daniel
        uid: 1000
    volumes:
      - ./app:/var/www/
      - /var/www/vendor/
    networks:
      - azapfyCte

  nginx:
      image: nginx:alpine
      restart: unless-stopped
      ports:
        - "80:80"
      volumes:
        - ./app:/var/www
        - ./docker/nginx/:/etc/nginx/conf.d/
      networks:
          - azapfyCte

  redis:
    image: redis:latest
    restart: unless-stopped
    command: redis-server --requirepass test-password
    ports:
      - "6379:6379"
    networks:
      - azapfyCte
  
networks:
    azapfyCte:
      driver: bridge    